# Site settings
title: BKBlog
description: "Dev Blog by BrandnewKorean"
url: "https://brandnewkorean.github.io"
baseurl: ""
lang: "ko_KR"
timezone: "Asia/Seoul"

#Author
author:
  name: BrandnewKorean
  email: brandnewkorean@naver.com
  url: "https://brandnewkorean.github.io"

#Posts
posts:
  url: /posts

#Plugins
plugins:
  - jekyll-paginate-v2

permalink: /posts/frontend/:num
pagination:
  enabled: true
  title: :title
  per_page: 15
  category: frontend
  sort_reverse: true
  sort_field: 'date'
  trail:
    before: 2
    after: 2
